import fs from 'node:fs';
import { execFileSync } from 'node:child_process';
const git = args => execFileSync('git', args, { encoding: 'utf8' }).trim();
if (git(['diff', '--cached', '--name-only'])) throw new Error('Index already contains changes: refusing to mix commits');
const source = fs.readFileSync('work/free_time_1/Package.mjs', 'utf8');
const files = [...source.matchAll(/^  '(src\/[^']+|tests\/[^']+)'/gm)].map(m => `work/production/${m[1]}`);
if (files.length !== 16) throw new Error('Unexpected source scope');
git(['add', '--', ...files, 'work/free_time_1/UiProbe/Program.cs', 'work/free_time_1/UiProbe/UiProbe.csproj', 'work/free_time_1/Package.mjs', 'work/free_time_1/Stage.mjs']);
const base = execFileSync('git', ['show', 'HEAD:.project-dashboard/roadmap.json'], { encoding: 'utf8' });
const current = JSON.parse(fs.readFileSync('.project-dashboard/roadmap.json', 'utf8'));
const calendar = current.items.find(i => i.id === 'PROD-03');
const id = base.indexOf('"id": "PROD-03"');
const begin = base.lastIndexOf('    {', id), end = base.indexOf('\n    },', id) + 6;
if (begin < 0 || end < id || !calendar) throw new Error('Dashboard scope invalid');
const replacement = JSON.stringify(calendar, null, 2).split('\n').map(line => `    ${line}`).join('\n');
const staged = base.slice(0, begin) + replacement + base.slice(end);
const before = JSON.parse(base);
const after = JSON.parse(staged);
const changed = after.items.filter(i => JSON.stringify(i) !== JSON.stringify(before.items.find(b => b.id === i.id))).map(i => i.id);
if (changed.join() !== 'PROD-03') throw new Error('Unrelated dashboard changes would be staged');
fs.writeFileSync('work/free_time_1/roadmap-for-index.json', staged);
const blob = execFileSync('git', ['hash-object', '-w', '--stdin'], { input: staged, encoding: 'utf8' }).trim();
git(['update-index', '--add', '--cacheinfo', `100644,${blob},.project-dashboard/roadmap.json`]);
fs.writeFileSync('work/free_time_1/source-scope.json', JSON.stringify(files, null, 2));
console.log(JSON.stringify({ sourceFiles: files.length, dashboardItems: changed, stagedTree: git(['write-tree']) }));
