<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Task.Application\Task.Application.csproj" />
    <ProjectReference Include="..\..\src\Task.Domain\Task.Domain.csproj" />
    <ProjectReference Include="..\..\src\Task.Infrastructure\Task.Infrastructure.csproj" />
  </ItemGroup>
</Project>
