namespace Task.Application.Audit;

/// <summary>
/// Persistence port for the organization append-only audit journal
/// (governance.audit_entries, migration 002, 7-year retention per product canon).
///
/// The journal is immutable: entries are never updated or deleted and their occurred_at
/// timestamps are assigned by the PostgreSQL server clock, so no write path through this
/// store can forge event time. Entries never carry passwords, tokens or secrets: the store
/// treats Metadata/OldState/NewState as opaque JSON (it neither interprets nor logs their
/// content) and only bounds Metadata size; keeping sensitive values out of the journal is
/// the responsibility of the writing service (separate package).
///
/// Reads are always scoped to exactly one organization and paginated with keyset
/// pagination ordered by (occurred_at, id) descending.
/// </summary>
public interface IAuditEntryStore
{
    /// <summary>
    /// Appends one immutable entry to the journal. The caller supplies Id, OrganizationId,
    /// CorrelationId and all business fields; the store intentionally ignores the exported
    /// AuditEntryRecord.OccurredAt and lets the database assign occurred_at via
    /// clock_timestamp() so that the event timestamp cannot be backdated or forward-dated.
    /// Metadata must not exceed 16 KiB (UTF-8), otherwise
    /// ArgumentOutOfRangeException is thrown.
    /// </summary>
    global::System.Threading.Tasks.Task AppendAsync(
        AuditEntryRecord entry,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Reads the journal of a single organization, newest first. Absent filters mean "all
    /// events of the organization"; an empty or whitespace filter value is treated as
    /// absent. PageToken is an opaque value returned by a previous call; when present the
    /// page continues immediately after the entry that produced the token.
    /// </summary>
    global::System.Threading.Tasks.Task<AuditPage> ReadAsync(
        AuditQuery query,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Immutable snapshot of one audit journal entry; it has no reference to any database
/// entity. Id, CorrelationId and RequestId are always generated by the caller, outside the
/// store. AuditEntryRecord.OccurredAt is populated from the database on reads; when the
/// record is used for appends the value is ignored and the database clock assigns the
/// actual occurred_at.
/// </summary>
public sealed record AuditEntryRecord(
    Guid Id,
    Guid OrganizationId,
    DateTimeOffset OccurredAt,
    Guid? ActorUserId,
    Guid? ActorSessionId,
    string ActionCode,
    string Outcome,
    string? ReasonCode,
    Guid CorrelationId,
    Guid RequestId,
    string Metadata,
    string? OldState,
    string? NewState,
    string RedactionLevel)
{
    /// <summary>Default empty JSON object for Metadata.</summary>
    public const string DefaultMetadata = "{}";
}

/// <summary>
/// Read request for an organization audit journal page. All filters are optional; absent
/// filters select every event of OrgId. PageSize defaults to 50 and is clamped by the store
/// to a maximum of 200.
/// </summary>
public sealed record AuditQuery(
    Guid OrgId,
    string? ActionFilter = null,
    string? OutcomeFilter = null,
    DateTimeOffset? FromUtc = null,
    DateTimeOffset? ToUtc = null,
    string? PageToken = null,
    int PageSize = 50);

/// <summary>
/// One page of the journal ordered by (occurred_at, id) descending. NextPageToken is set
/// only when further pages exist after Entries; pass it back in AuditQuery.PageToken to
/// continue the same ordered walk.
/// </summary>
public sealed record AuditPage(
    IReadOnlyList<AuditEntryRecord> Entries,
    string? NextPageToken);